// packages/dragdoll-react-docs/examples/002-draggable-auto-scroll/index.tsx
import { autoScrollPlugin } from 'dragdoll';
import { DndContextProvider, useDraggable } from 'dragdoll-react';
import { StrictMode, useCallback, useEffect, useRef } from 'react';
import { createRoot } from 'react-dom/client';

function AutoScrollCard() {
  const containerRef = useRef<HTMLDivElement | null>(null);
  const elementRef = useRef<HTMLButtonElement | null>(null);

  const { draggable, ref } = useDraggable({
    element: elementRef.current,
    pointerSensor: true,
    keyboardMotionSensor: { computeSpeed: () => 100 },
    container: containerRef.current,
    frozenStyles: () => ['left', 'top'],
    onStart: (drag) => {
      drag.items[0].element.classList.add('dragging');
    },
    onEnd: (drag) => {
      drag.items[0].element.classList.remove('dragging');
    },
  });

  useEffect(() => {
    if (!draggable) return;

    draggable.use(
      autoScrollPlugin({
        targets: [
          {
            element: window,
            axis: 'y',
            padding: { top: Infinity, bottom: Infinity },
          },
        ],
      }),
    );
  }, [draggable]);

  const handleRef = useCallback(
    (node: HTMLButtonElement | null) => {
      elementRef.current = node;
      ref(node);
    },
    [ref],
  );

  return (
    <>
      <div ref={containerRef} className="drag-container" />
      <div className="card-container">
        <button ref={handleRef} className="card draggable" type="button" aria-label="Draggable" />
      </div>
    </>
  );
}

function App() {
  return (
    <DndContextProvider>
      <AutoScrollCard />
    </DndContextProvider>
  );
}

const container = document.getElementById('root');

if (container) {
  createRoot(container).render(
    <StrictMode>
      <App />
    </StrictMode>,
  );
}

// packages/dragdoll-docs/examples/solid/002-draggable-auto-scroll/index.tsx
/** @jsxImportSource solid-js */
import {
  useDraggable,
  useDraggableAutoScroll,
  useDraggableDrag,
  useKeyboardMotionSensor,
  usePointerSensor,
} from 'dragdoll-solid';
import { render } from 'solid-js/web';

function DraggableCard() {
  let element: HTMLDivElement | null = null;
  const [pointerSensor, setPointerSensorRef] = usePointerSensor();
  const [keyboardSensor, setKeyboardSensorRef] = useKeyboardMotionSensor({
    computeSpeed: () => 100,
  });

  const draggable = useDraggableAutoScroll(
    useDraggable([pointerSensor, keyboardSensor], () => ({
      elements: () => (element ? [element] : []),
    })),
    {
      targets: [
        {
          element: window,
          axis: 'y' as const,
          padding: { top: Infinity, bottom: Infinity },
        },
      ],
    },
  );

  const drag = useDraggableDrag(draggable);

  const setRefs = (node: HTMLDivElement) => {
    element = node;
    setPointerSensorRef(node);
    setKeyboardSensorRef(node);
  };

  return (
    <div ref={setRefs} class={`card draggable ${drag() ? 'dragging' : ''}`} tabIndex={0}>
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
        <path d="M278.6 9.4c-12.5-12.5-32.8-12.5-45.3 0l-64 64c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0l9.4-9.4L224 224l-114.7 0 9.4-9.4c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0l-64 64c-12.5 12.5-12.5 32.8 0 45.3l64 64c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3l-9.4-9.4L224 288l0 114.7-9.4-9.4c-12.5-12.5-32.8-12.5-45.3 0s-12.5 32.8 0 45.3l64 64c12.5 12.5 32.8 12.5 45.3 0l64-64c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0l-9.4 9.4L288 288l114.7 0-9.4 9.4c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0l64-64c12.5-12.5 12.5-32.8 0-45.3l-64-64c-12.5-12.5-32.8-12.5-45.3 0s-12.5 32.8 0 45.3l9.4 9.4L288 224l0-114.7 9.4 9.4c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3l-64-64z" />
      </svg>
    </div>
  );
}

function App() {
  return (
    <div class="card-container-outer">
      <div class="card-container">
        <DraggableCard />
      </div>
    </div>
  );
}

const root = document.getElementById('root');
if (!root) {
  throw new Error('Failed to find the root element');
}

render(() => <App />, root);
