// packages/dragdoll-solid/src/hooks/use-dnd-observer-callback.ts
import type { DndObserver, DndObserverEventCallbacks } from 'dragdoll/dnd-observer';
import type { CollisionData } from 'dragdoll/dnd-observer/collision-detector';
import { createEffect, createMemo, createSignal, onCleanup } from 'solid-js';
import type { MaybeAccessor } from '../utils/maybe-accessor.js';
import { resolveMaybeAccessor } from '../utils/maybe-accessor.js';
import { useDndObserverContext } from './use-dnd-observer-context.js';

export function useDndObserverCallback<
  T extends CollisionData = CollisionData,
  K extends keyof DndObserverEventCallbacks<T> = keyof DndObserverEventCallbacks<T>,
>(
  eventType: K,
  callback: MaybeAccessor<DndObserverEventCallbacks<T>[K] | undefined>,
  dndObserver?: MaybeAccessor<DndObserver<T> | null>,
) {
  const observerFromContext = useDndObserverContext<T>();
  const effectiveObserver = createMemo(() => {
    if (dndObserver === undefined) return observerFromContext();
    return resolveMaybeAccessor(dndObserver);
  });

  let resolvedCallback: DndObserverEventCallbacks<T>[K] | undefined;
  const [hasCallback, setHasCallback] = createSignal(false);

  createEffect(() => {
    resolvedCallback = resolveMaybeAccessor(callback);
    setHasCallback(Boolean(resolvedCallback));
  });

  createEffect(() => {
    const observer = effectiveObserver();
    if (!observer || !hasCallback()) return;
    const listener = ((...args: any[]) => {
      (resolvedCallback as ((...innerArgs: any[]) => void) | undefined)?.(...args);
    }) as DndObserverEventCallbacks<T>[K];
    const listenerId = observer.on(eventType, listener);
    onCleanup(() => observer.off(eventType, listenerId));
  });
}

// packages/dragdoll-react/src/hooks/use-dnd-observer-callback.ts
import { DndObserver, DndObserverEventCallbacks } from 'dragdoll/dnd-observer';
import type { CollisionData } from 'dragdoll/dnd-observer/collision-detector';
import { useRef } from 'react';
import { useDndObserverContext } from './use-dnd-observer-context.js';
import { useIsomorphicLayoutEffect } from './use-isomorphic-layout-effect.js';

export function useDndObserverCallback<
  T extends CollisionData = CollisionData,
  K extends keyof DndObserverEventCallbacks<T> = keyof DndObserverEventCallbacks<T>,
>(eventType: K, callback?: DndObserverEventCallbacks<T>[K], dndObserver?: DndObserver<T> | null) {
  const dndObserverFromContext = useDndObserverContext<T>();
  const effectiveDndObserver = dndObserver === undefined ? dndObserverFromContext : dndObserver;
  const hasCallback = !!callback;
  const callbackRef = useRef(callback);
  callbackRef.current = callback;

  useIsomorphicLayoutEffect(() => {
    if (!effectiveDndObserver || !hasCallback) return;
    const listener = ((...args: any[]) => {
      (callbackRef.current as ((...args: any[]) => void) | undefined)?.(...args);
    }) as DndObserverEventCallbacks<T>[K];
    const id = effectiveDndObserver.on(eventType, listener);
    return () => void effectiveDndObserver.off(eventType, id);
  }, [eventType, effectiveDndObserver, hasCallback]);
}
