// packages/dragdoll-react/src/hooks/use-keyboard-motion-sensor.ts
import type {
  KeyboardMotionSensorEvents,
  KeyboardMotionSensorSettings,
} from 'dragdoll/sensors/keyboard-motion';
import { KeyboardMotionSensor } from 'dragdoll/sensors/keyboard-motion';
import { useRef, useState } from 'react';
import { useCallbackStable } from './use-callback-stable.js';
import { useIsomorphicLayoutEffect } from './use-isomorphic-layout-effect.js';
import { useMemoStable } from './use-memo-stable.js';

export function useKeyboardMotionSensor<
  E extends KeyboardMotionSensorEvents = KeyboardMotionSensorEvents,
>(settings: Partial<KeyboardMotionSensorSettings<E>> = {}, element?: Element | null) {
  const [sensor, setSensor] = useState<KeyboardMotionSensor<E> | null>(null);
  const sensorRef = useRef<KeyboardMotionSensor<E> | null>(sensor);
  const settingsRef = useRef(settings);

  // Helper function to create a new keyboard sensor.
  const createSensor = useCallbackStable((node: Element | null) => {
    sensorRef.current?.destroy();
    const newSensor = new KeyboardMotionSensor<E>(node, settingsRef.current);
    sensorRef.current = newSensor;
    setSensor(newSensor);
  }, []);

  // Helper function to destroy the keyboard sensor.
  const destroySensor = useCallbackStable(() => {
    if (!sensorRef.current) return;
    sensorRef.current.destroy();
    sensorRef.current = null;
    setSensor(null);
  }, []);

  // Ref callback for the keyboard sensor element IF user does not provide an
  // explicit element.
  const setRef = useCallbackStable(
    (node: Element | null) => {
      // If user provides an explicit element or null, do not create a new
      // keyboard sensor.
      if (element !== undefined) return;

      // Destroy the keyboard sensor if the node is null.
      if (node === null) {
        destroySensor();
        return;
      }

      // Create a new keyboard sensor if there is no sensor or the node has
      // changed.
      const currentSensor = sensorRef.current;
      if (!currentSensor || currentSensor.element !== node) {
        createSensor(node);
      }
    },
    [element, createSensor, destroySensor],
  );

  // Keep the settings up to date.
  settingsRef.current = settings;

  // Handle explicit element change.
  useIsomorphicLayoutEffect(() => {
    if (element === undefined) return;
    createSensor(element);
    return destroySensor;
  }, [element, createSensor, destroySensor]);

  // Handle settings change.
  useIsomorphicLayoutEffect(() => {
    if (sensor) sensor.updateSettings(settings);
  }, [sensor, settings]);

  return useMemoStable(() => {
    return [sensor, setRef] as const;
  }, [sensor, setRef]);
}

// packages/dragdoll-solid/src/hooks/use-keyboard-motion-sensor.ts
import type {
  KeyboardMotionSensorEvents,
  KeyboardMotionSensorSettings,
} from 'dragdoll/sensors/keyboard-motion';
import { KeyboardMotionSensor } from 'dragdoll/sensors/keyboard-motion';
import type { Accessor } from 'solid-js';
import { createEffect, createMemo, createSignal, onCleanup } from 'solid-js';
import type { MaybeAccessor } from '../utils/maybe-accessor.js';
import { resolveMaybeAccessor } from '../utils/maybe-accessor.js';

export function useKeyboardMotionSensor<
  E extends KeyboardMotionSensorEvents = KeyboardMotionSensorEvents,
>(
  settings: MaybeAccessor<Partial<KeyboardMotionSensorSettings<E>> | undefined> = {},
  element?: MaybeAccessor<Element | null>,
): readonly [Accessor<KeyboardMotionSensor<E> | null>, (node: Element | null) => void] {
  const resolvedSettings = createMemo(() => resolveMaybeAccessor(settings, {}) || {});
  const resolvedElement = createMemo(() =>
    element === undefined ? undefined : resolveMaybeAccessor(element),
  );

  const [sensor, setSensor] = createSignal<KeyboardMotionSensor<E> | null>(null);
  let sensorRef: KeyboardMotionSensor<E> | null = null;

  const destroySensor = () => {
    if (!sensorRef) return;
    sensorRef.destroy();
    sensorRef = null;
    setSensor(null);
  };

  const createSensor = (node: Element | null) => {
    sensorRef?.destroy();
    const newSensor = new KeyboardMotionSensor<E>(node, resolvedSettings());
    sensorRef = newSensor;
    setSensor(newSensor);
  };

  createEffect(() => {
    const current = sensorRef;
    if (current) current.updateSettings(resolvedSettings());
  });

  createEffect(() => {
    const explicitElement = resolvedElement();
    if (explicitElement === undefined) return;
    createSensor(explicitElement);
    onCleanup(destroySensor);
  });

  const setRef = (node: Element | null) => {
    if (element !== undefined) return;
    if (node === null) {
      destroySensor();
      return;
    }
    if (sensorRef?.element === node) return;
    createSensor(node);
  };

  onCleanup(destroySensor);

  return [sensor, setRef] as const;
}
