// packages/dragdoll-react-tests/src/utils/test-wrapper.tsx
import type { DndObserver } from 'dragdoll/dnd-observer';
import { DndObserverContext } from 'dragdoll-react';
import type { ReactNode } from 'react';

export function DndProvider({
  observer,
  children,
}: {
  observer: DndObserver<any>;
  children: ReactNode;
}) {
  return <DndObserverContext.Provider value={observer}>{children}</DndObserverContext.Provider>;
}

// packages/dragdoll-solid-tests/src/utils/test-wrapper.tsx
import type { DndObserver } from 'dragdoll/dnd-observer';
import { DndObserverContext } from 'dragdoll-solid';
import type { JSX } from 'solid-js';

export function DndProvider(props: { observer: DndObserver<any>; children: JSX.Element }) {
  return (
    <DndObserverContext.Provider value={() => props.observer}>
      {props.children}
    </DndObserverContext.Provider>
  );
}
