// packages/dragdoll-docs/solid-examples/008-draggable-drag-handle/index.tsx
/** @jsxImportSource solid-js */
import { PointerSensor } from 'dragdoll';
import {
  useDraggable,
  useDraggableDrag,
  UseDraggableSettings,
  useKeyboardMotionSensor,
  usePointerSensor,
} from 'dragdoll-solid';
import { createSignal } from 'solid-js';
import { render } from 'solid-js/web';

function DraggableCard() {
  let element: HTMLDivElement | null = null;
  const [pointerSensor, setPointerSensorRef] = usePointerSensor();
  const [keyboardSensor, setKeyboardSensorRef] = useKeyboardMotionSensor();
  const [sensorType, setSensorType] = createSignal<'pointer' | 'keyboard' | null>(null);

  const draggableSettings: UseDraggableSettings = {
    elements: () => (element ? [element] : []),
    onStart: (drag) => {
      setSensorType(drag.sensor instanceof PointerSensor ? 'pointer' : 'keyboard');
    },
    onEnd: () => {
      setSensorType(null);
    },
  };

  const draggable = useDraggable([pointerSensor, keyboardSensor], draggableSettings);
  const drag = useDraggableDrag(draggable);

  const setElementRef = (node: HTMLDivElement) => {
    element = node;
    setKeyboardSensorRef(node);
  };

  return (
    <div
      ref={setElementRef}
      class={`card draggable ${drag() ? 'dragging' : ''} ${drag() && sensorType() ? `${sensorType()}-dragging` : ''}`}
      tabIndex={0}
    >
      <div ref={setPointerSensorRef} class="handle">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
          <path d="M278.6 9.4c-12.5-12.5-32.8-12.5-45.3 0l-64 64c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0l9.4-9.4L224 224l-114.7 0 9.4-9.4c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0l-64 64c-12.5 12.5-12.5 32.8 0 45.3l64 64c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3l-9.4-9.4L224 288l0 114.7-9.4-9.4c-12.5-12.5-32.8-12.5-45.3 0s-12.5 32.8 0 45.3l64 64c12.5 12.5 32.8 12.5 45.3 0l64-64c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0l-9.4 9.4L288 288l114.7 0-9.4 9.4c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0l64-64c12.5-12.5 12.5-32.8 0-45.3l-64-64c-12.5-12.5-32.8-12.5-45.3 0s-12.5 32.8 0 45.3l9.4 9.4L288 224l0-114.7 9.4 9.4c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3l-64-64z" />
        </svg>
      </div>
    </div>
  );
}

function App() {
  return <DraggableCard />;
}

const root = document.getElementById('root');
if (!root) {
  throw new Error('Failed to find the root element');
}

render(() => <App />, root);

// packages/dragdoll-react-docs/examples/008-draggable-drag-handle/index.tsx
import type { Sensor } from 'dragdoll';
import { KeyboardSensor, PointerSensor } from 'dragdoll';
import { DndContextProvider, useDraggable } from 'dragdoll-react';
import { StrictMode, useCallback, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';

function DragHandleCard() {
  const [buttonNode, setButtonNode] = useState<HTMLButtonElement | null>(null);
  const [handleNode, setHandleNode] = useState<HTMLDivElement | null>(null);
  const [sensors, setSensors] = useState<Sensor[] | undefined>(undefined);

  useEffect(() => {
    if (!buttonNode || !handleNode) return;
    if (sensors) return;
    setSensors([new PointerSensor(handleNode), new KeyboardSensor(buttonNode)]);
  }, [buttonNode, handleNode, sensors]);

  const { ref } = useDraggable({
    element: sensors ? buttonNode : null,
    pointerSensor: false,
    keyboardSensor: false,
    sensors,
    onStart: (drag) => {
      const element = drag.items[0].element;
      element.classList.add('dragging');
      if (drag.sensor instanceof PointerSensor) {
        element.classList.add('pointer-dragging');
      } else {
        element.classList.add('keyboard-dragging');
      }
    },
    onEnd: (drag) => {
      const element = drag.items[0].element;
      element.classList.remove('dragging', 'pointer-dragging', 'keyboard-dragging');
    },
  });

  useEffect(() => {
    if (!buttonNode || !sensors) return;
    ref(buttonNode);
    return () => {
      ref(null);
    };
  }, [buttonNode, sensors, ref]);

  const handleButtonRef = useCallback((node: HTMLButtonElement | null) => {
    setButtonNode(node);
  }, []);

  const handleHandleRef = useCallback((node: HTMLDivElement | null) => {
    setHandleNode(node);
    if (!node) {
      setSensors(undefined);
    }
  }, []);

  return (
    <button
      ref={handleButtonRef}
      className="card draggable"
      type="button"
      aria-label="Handle draggable"
    >
      <div ref={handleHandleRef} className="handle" aria-hidden="true">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
          <path
            fill="currentColor"
            d="M32 96C32 60.7 60.7 32 96 32h64c35.3 0 64 28.7 64 64v64c0 35.3-28.7 64-64 64h-64c-35.3 0-64-28.7-64-64V96zm256 0c0-35.3 28.7-64 64-64h64c35.3 0 64 28.7 64 64v64c0 35.3-28.7 64-64 64h-64c-35.3 0-64-28.7-64-64V96zM32 320c0-35.3 28.7-64 64-64h64c35.3 0 64 28.7 64 64v64c0 35.3-28.7 64-64 64h-64c-35.3 0-64-28.7-64-64V320zm256 0c0-35.3 28.7-64 64-64h64c35.3 0 64 28.7 64 64v64c0 35.3-28.7 64-64 64h-64c-35.3 0-64-28.7-64-64V320z"
          />
        </svg>
      </div>
    </button>
  );
}

function App() {
  return (
    <DndContextProvider>
      <DragHandleCard />
    </DndContextProvider>
  );
}

const container = document.getElementById('root');

if (container) {
  createRoot(container).render(
    <StrictMode>
      <App />
    </StrictMode>,
  );
}
