// packages/dragdoll-docs/examples/react/010-draggable-start-threshold/index.tsx
import { DraggableModifier, PointerSensor, startOffsetModifier } from 'dragdoll';
import {
  useDraggable,
  useDraggableDrag,
  UseDraggableSettings,
  usePointerSensor,
} from 'dragdoll-react';
import { memo, StrictMode, useCallback, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';

const THRESHOLD = 5;

const DraggableCardMemo = memo(function DraggableCard() {
  const elementRef = useRef<HTMLAnchorElement>(null);
  const [zIndex, setZIndex] = useState(1);
  const zIndexRef = useRef(1);
  const [pointerSensor, setPointerSensorRef] = usePointerSensor();

  const draggableSettings: UseDraggableSettings<PointerSensor> = useMemo(
    () => ({
      elements: () => (elementRef.current ? [elementRef.current] : []),
      startPredicate: ({ event }) => {
        const dx = event.x - event.startX;
        const dy = event.y - event.startY;
        return Math.sqrt(dx * dx + dy * dy) >= THRESHOLD ? true : undefined;
      },
      positionModifiers: [startOffsetModifier as unknown as DraggableModifier<PointerSensor>],
      onStart: () => {
        setZIndex(++zIndexRef.current);
      },
    }),
    [],
  );

  const draggable = useDraggable([pointerSensor], draggableSettings);
  const drag = useDraggableDrag(draggable);

  const setRefs = useCallback(
    (node: HTMLAnchorElement | null) => {
      elementRef.current = node;
      setPointerSensorRef(node);
    },
    [setPointerSensorRef],
  );

  return (
    <a
      ref={setRefs}
      href="https://muuri.dev"
      className={`card draggable ${drag ? 'dragging' : ''}`}
      style={{ zIndex }}
      target="_blank"
      rel="noopener noreferrer"
      draggable={false}
    >
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 512">
        <path d="M579.8 267.7c56.5-56.5 56.5-148 0-204.5c-50-50-128.8-56.5-186.3-15.4l-1.6 1.1c-14.4 10.3-17.7 30.3-7.4 44.6s30.3 17.7 44.6 7.4l1.6-1.1c32.1-22.9 76-19.3 103.8 8.6c31.5 31.5 31.5 82.5 0 114L422.3 334.8c-31.5 31.5-82.5 31.5-114 0c-27.9-27.9-31.5-71.8-8.6-103.8l1.1-1.6c10.3-14.4 6.9-34.4-7.4-44.6s-34.4-6.9-44.6 7.4l-1.1 1.6C680.8 251.2 170.6 330 220.6 380c56.5 56.5 148 56.5 204.5 0L579.8 267.7zM60.2 244.3c-56.5 56.5-56.5 148 0 204.5c50 50 128.8 56.5 186.3 15.4l1.6-1.1c14.4-10.3 17.7-30.3 7.4-44.6s-30.3-17.7-44.6-7.4l-1.6 1.1c-32.1 22.9-76 19.3-103.8-8.6C74 372.1 74 321.1 105.5 289.5L217.7 177.2c31.5-31.5 82.5-31.5 114 0c27.9 27.9 31.5 71.8 8.6 103.9l-1.1 1.6c-10.3 14.4-6.9 34.4 7.4 44.6s34.4 6.9 44.6-7.4l1.1-1.6C540.8 260.8 470.6 182 420.6 132c-56.5-56.5-148-56.5-204.5 0L60.2 244.3z" />
      </svg>
      <span>muuri.dev</span>
    </a>
  );
});

function App() {
  return <DraggableCardMemo />;
}

const rootElement = document.getElementById('root');
if (!rootElement) {
  throw new Error('Failed to find the root element');
}

const root = createRoot(rootElement);
root.render(
  <StrictMode>
    <App />
  </StrictMode>,
);

// packages/dragdoll-docs/examples/solid/010-draggable-start-threshold/index.tsx
/** @jsxImportSource solid-js */
import { DraggableModifier, PointerSensor, startOffsetModifier } from 'dragdoll';
import {
  useDraggable,
  useDraggableDrag,
  UseDraggableSettings,
  usePointerSensor,
} from 'dragdoll-solid';
import { createSignal } from 'solid-js';
import { render } from 'solid-js/web';

const THRESHOLD = 5;

function DraggableCard() {
  let element: HTMLAnchorElement | null = null;
  const [zIndex, setZIndex] = createSignal(1);
  let zIndexCounter = 1;
  const [pointerSensor, setPointerSensorRef] = usePointerSensor();

  const draggableSettings: UseDraggableSettings<PointerSensor> = {
    elements: () => (element ? [element] : []),
    startPredicate: ({ event }) => {
      const dx = event.x - event.startX;
      const dy = event.y - event.startY;
      return Math.sqrt(dx * dx + dy * dy) >= THRESHOLD ? true : undefined;
    },
    positionModifiers: [startOffsetModifier as unknown as DraggableModifier<PointerSensor>],
    onStart: () => {
      setZIndex(++zIndexCounter);
    },
  };

  const draggable = useDraggable([pointerSensor], draggableSettings);
  const drag = useDraggableDrag(draggable);

  const setRefs = (node: HTMLAnchorElement) => {
    element = node;
    setPointerSensorRef(node);
  };

  return (
    <a
      ref={setRefs}
      href="https://muuri.dev"
      class={`card draggable ${drag() ? 'dragging' : ''}`}
      style={{ 'z-index': zIndex() }}
      target="_blank"
      rel="noopener noreferrer"
      draggable={false}
    >
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 512">
        <path d="M579.8 267.7c56.5-56.5 56.5-148 0-204.5c-50-50-128.8-56.5-186.3-15.4l-1.6 1.1c-14.4 10.3-17.7 30.3-7.4 44.6s30.3 17.7 44.6 7.4l1.6-1.1c32.1-22.9 76-19.3 103.8 8.6c31.5 31.5 31.5 82.5 0 114L422.3 334.8c-31.5 31.5-82.5 31.5-114 0c-27.9-27.9-31.5-71.8-8.6-103.8l1.1-1.6c10.3-14.4 6.9-34.4-7.4-44.6s-34.4-6.9-44.6 7.4l-1.1 1.6C680.8 251.2 170.6 330 220.6 380c56.5 56.5 148 56.5 204.5 0L579.8 267.7zM60.2 244.3c-56.5 56.5-56.5 148 0 204.5c50 50 128.8 56.5 186.3 15.4l1.6-1.1c14.4-10.3 17.7-30.3 7.4-44.6s-30.3-17.7-44.6-7.4l-1.6 1.1c-32.1 22.9-76 19.3-103.8-8.6C74 372.1 74 321.1 105.5 289.5L217.7 177.2c31.5-31.5 82.5-31.5 114 0c27.9 27.9 31.5 71.8 8.6 103.9l-1.1 1.6c-10.3 14.4-6.9 34.4 7.4 44.6s34.4 6.9 44.6-7.4l1.1-1.6C540.8 260.8 470.6 182 420.6 132c-56.5-56.5-148-56.5-204.5 0L60.2 244.3z" />
      </svg>
      <span>muuri.dev</span>
    </a>
  );
}

function App() {
  return <DraggableCard />;
}

const root = document.getElementById('root');
if (!root) {
  throw new Error('Failed to find the root element');
}

render(() => <App />, root);
