// packages/dragdoll-react-docs/examples/007-draggable-center-to-pointer/index.tsx
import { PointerSensor } from 'dragdoll';
import { DndContextProvider, Draggable } from 'dragdoll-react';
import { StrictMode, useMemo } from 'react';
import { createRoot } from 'react-dom/client';

function CenterCard() {
  const modifiers = useMemo(
    () => [
      (change: { x: number; y: number }, { drag, item, phase }: any) => {
        if (
          phase === 'start' &&
          drag.sensor instanceof PointerSensor &&
          drag.items[0].element === item.element
        ) {
          const { clientRect } = item;
          const { x, y } = drag.startEvent;
          change.x = x - (clientRect.x + clientRect.width / 2);
          change.y = y - (clientRect.y + clientRect.height / 2);
        }
        return change;
      },
    ],
    [],
  );

  return (
    <Draggable
      pointerSensor
      keyboardSensor
      positionModifiers={modifiers}
      onStart={(drag) => drag.items[0].element.classList.add('dragging')}
      onEnd={(drag) => drag.items[0].element.classList.remove('dragging')}
    >
      <button className="card draggable" type="button" aria-label="Centered draggable" />
    </Draggable>
  );
}

function App() {
  return (
    <DndContextProvider>
      <CenterCard />
    </DndContextProvider>
  );
}

const container = document.getElementById('root');

if (container) {
  createRoot(container).render(
    <StrictMode>
      <App />
    </StrictMode>,
  );
}

// packages/dragdoll-docs/examples/solid/007-draggable-center-to-pointer/index.tsx
/** @jsxImportSource solid-js */
import { PointerSensor } from 'dragdoll';
import {
  useDraggable,
  useDraggableDrag,
  UseDraggableSettings,
  useKeyboardMotionSensor,
  usePointerSensor,
} from 'dragdoll-solid';
import { render } from 'solid-js/web';

function DraggableCard() {
  let element: HTMLDivElement | null = null;
  const [pointerSensor, setPointerSensorRef] = usePointerSensor();
  const [keyboardSensor, setKeyboardSensorRef] = useKeyboardMotionSensor();

  const draggableSettings: UseDraggableSettings = {
    elements: () => (element ? [element] : []),
    positionModifiers: [
      (change, { drag, item, phase }) => {
        // Align the dragged element so that the pointer
        // is in the center of the element.
        if (phase === 'start' && drag.sensor instanceof PointerSensor) {
          const { clientRect } = item;
          const { x, y } = drag.startEvent;
          const targetX = clientRect.x + clientRect.width / 2;
          const targetY = clientRect.y + clientRect.height / 2;
          change.x = x - targetX;
          change.y = y - targetY;
        }
        return change;
      },
    ],
  };

  const draggable = useDraggable([pointerSensor, keyboardSensor], draggableSettings);
  const drag = useDraggableDrag(draggable);

  const setRefs = (node: HTMLDivElement) => {
    element = node;
    setPointerSensorRef(node);
    setKeyboardSensorRef(node);
  };

  return (
    <div ref={setRefs} class={`card draggable ${drag() ? 'dragging' : ''}`} tabIndex={0}>
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
        <path d="M278.6 9.4c-12.5-12.5-32.8-12.5-45.3 0l-64 64c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0l9.4-9.4L224 224l-114.7 0 9.4-9.4c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0l-64 64c-12.5 12.5-12.5 32.8 0 45.3l64 64c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3l-9.4-9.4L224 288l0 114.7-9.4-9.4c-12.5-12.5-32.8-12.5-45.3 0s-12.5 32.8 0 45.3l64 64c12.5 12.5 32.8 12.5 45.3 0l64-64c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0l-9.4 9.4L288 288l114.7 0-9.4 9.4c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0l64-64c12.5-12.5 12.5-32.8 0-45.3l-64-64c-12.5-12.5-32.8-12.5-45.3 0s-12.5 32.8 0 45.3l9.4 9.4L288 224l0-114.7 9.4 9.4c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3l-64-64z" />
      </svg>
    </div>
  );
}

function App() {
  return <DraggableCard />;
}

const root = document.getElementById('root');
if (!root) {
  throw new Error('Failed to find the root element');
}

render(() => <App />, root);
