// packages/dragdoll-solid/src/hooks/use-droppable.ts
import type { DndObserver } from 'dragdoll/dnd-observer';
import type { DroppableOptions } from 'dragdoll/droppable';
import { Droppable as DroppableCore } from 'dragdoll/droppable';
import { createEffect, createMemo, createSignal, onCleanup } from 'solid-js';
import type { MaybeAccessor } from '../utils/maybe-accessor.js';
import { resolveMaybeAccessor } from '../utils/maybe-accessor.js';
import { useDndObserverContext } from './use-dnd-observer-context.js';

export interface UseDroppableSettings extends DroppableOptions {
  element?: HTMLElement | SVGSVGElement;
  dndObserver?: DndObserver<any> | null;
}

export function useDroppable(settingsInput?: MaybeAccessor<UseDroppableSettings | undefined>) {
  const resolvedSettings = createMemo(() => resolveMaybeAccessor(settingsInput));
  const elementAccessor = createMemo(() => resolvedSettings()?.element);
  const overrideObserver = createMemo(() => resolvedSettings()?.dndObserver);
  const idAccessor = createMemo(() => resolvedSettings()?.id);
  const acceptAccessor = createMemo(() => resolvedSettings()?.accept);
  const dataAccessor = createMemo(() => resolvedSettings()?.data);

  const observerFromContext = useDndObserverContext<any>();
  const effectiveObserver = createMemo(() => {
    const override = overrideObserver();
    return override === undefined ? observerFromContext() : override;
  });

  const [droppable, setDroppable] = createSignal<DroppableCore | null>(null);
  let droppableRef: DroppableCore | null = null;
  let appliedId = idAccessor();
  let appliedObserver = effectiveObserver();

  const destroyDroppable = () => {
    if (!droppableRef) return;
    droppableRef.destroy();
    droppableRef = null;
    setDroppable(null);
  };

  const createDroppableInstance = (node: HTMLElement | SVGSVGElement) => {
    destroyDroppable();
    const options: DroppableOptions = {
      id: idAccessor(),
      accept: acceptAccessor(),
      data: dataAccessor(),
    };
    const instance = new DroppableCore(node, options);
    droppableRef = instance;
    appliedId = options.id;
    const observer = effectiveObserver();
    if (observer) observer.addDroppables([instance]);
    appliedObserver = observer;
    setDroppable(instance);
  };

  const setRef = (node: HTMLElement | SVGSVGElement | null) => {
    if (elementAccessor() !== undefined) return;
    if (node === null) {
      destroyDroppable();
      return;
    }
    if (droppableRef?.element === node) return;
    createDroppableInstance(node);
  };

  createEffect(() => {
    const explicitElement = elementAccessor();
    if (explicitElement === undefined) return;
    if (explicitElement === null) {
      destroyDroppable();
      return;
    }
    createDroppableInstance(explicitElement);
    onCleanup(destroyDroppable);
  });

  createEffect(() => {
    const droppable = droppableRef;
    if (!droppable) return;
    const nextId = idAccessor();
    if (appliedId === nextId) return;
    createDroppableInstance(droppable.element);
  });

  createEffect(() => {
    const currentObserver = effectiveObserver();
    if (appliedObserver === currentObserver) return;
    const droppable = droppableRef;
    if (droppable) {
      appliedObserver?.removeDroppables([droppable]);
      currentObserver?.addDroppables([droppable]);
    }
    appliedObserver = currentObserver;
  });

  createEffect(() => {
    const droppable = droppableRef;
    if (!droppable) return;
    const nextAccept = acceptAccessor() || (() => true);
    droppable.accept = nextAccept;
  });

  createEffect(() => {
    const droppable = droppableRef;
    if (!droppable) return;
    droppable.data = dataAccessor() || {};
  });

  onCleanup(destroyDroppable);

  return [droppable, setRef] as const;
}

// packages/dragdoll-react/src/droppable/use-droppable.ts
import type { DroppableOptions } from 'dragdoll';
import { Droppable } from 'dragdoll';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { useDndContext } from '../dnd-context/use-dnd-context.js';
import type { UseDroppableOptions, UseDroppableReturn } from '../types.js';

export function useDroppable({
  element,
  id,
  accept,
  data,
}: UseDroppableOptions): UseDroppableReturn {
  const droppableRef = useRef<Droppable | null>(null);
  const [droppable, setDroppable] = useState<Droppable | null>(null);
  const dndContext = useDndContext().context;
  const elementRef = useRef<HTMLElement | SVGSVGElement | null>(null);

  const createDroppable = useCallback(() => {
    if (!elementRef.current || droppableRef.current) return;

    const options: DroppableOptions = {
      id,
      accept,
      data,
    };

    const instance = new Droppable(elementRef.current, options);
    droppableRef.current = instance;
    setDroppable(instance);

    dndContext.addDroppables([instance]);

    return instance;
  }, [id, accept, data, dndContext]);

  const setRef = useCallback(
    (el: HTMLElement | SVGSVGElement | null) => {
      elementRef.current = el;
      if (el && !droppableRef.current) {
        createDroppable();
      }
    },
    [createDroppable],
  );

  useEffect(() => {
    elementRef.current = element;
    if (element && !droppableRef.current) {
      createDroppable();
    }
  }, [element, createDroppable]);

  useEffect(() => {
    if (droppableRef.current) {
      if (accept !== undefined) {
        droppableRef.current.accept = accept;
      }
      if (data !== undefined) {
        droppableRef.current.data = data;
      }
    }
  }, [accept, data]);

  useEffect(() => {
    return () => {
      if (droppableRef.current) {
        dndContext.removeDroppables([droppableRef.current]);
        droppableRef.current.destroy();
        droppableRef.current = null;
        setDroppable(null);
      }
    };
  }, [dndContext]);

  return useMemo(
    () => ({
      droppable,
      ref: setRef,
    }),
    [droppable, setRef],
  );
}
